// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MeshPointsML.Model
{
    public class ModelInput
    {
        [ColumnName("x5"), LoadColumn(0)]
        public float X5 { get; set; }


        [ColumnName("y5"), LoadColumn(1)]
        public float Y5 { get; set; }


        [ColumnName("x6"), LoadColumn(2)]
        public float X6 { get; set; }


        [ColumnName("y6"), LoadColumn(3)]
        public float Y6 { get; set; }


        [ColumnName("x9"), LoadColumn(4)]
        public float X9 { get; set; }


        [ColumnName("y9"), LoadColumn(5)]
        public float Y9 { get; set; }


        [ColumnName("x10"), LoadColumn(6)]
        public float X10 { get; set; }


        [ColumnName("y10"), LoadColumn(7)]
        public float Y10 { get; set; }


        [ColumnName("avg_jacobian"), LoadColumn(8)]
        public float Avg_jacobian { get; set; }


    }
}
